### PR TITLE
Feature/8 slf4j

### PR DESCRIPTION
**Pull request by dzuvic**
pull request for #8

### CODE REVIEW

**Comment by romanroe** [comment]
Sounds good. But why a SNAPSHOT version?

**Comment by dzuvic** [comment]
Several Reasons:

* mvn might use the local parent pom taken from the local repository. Either always do mvn install when changing anything  in the parent pom or use SNAPSHOT as version. Maven discards in this case the local repository. Since first might interfere with other local build second is the better option.
* Maven does this by itself (see: https://github.com/apache/maven/blob/master/pom.xml ), and therefore most of maven plugins, e.g. release plugin.
* no accidental deployments of on major repositories, like Maven Central.

**Comment by romanroe** [comment]
Makes sense. However, for automation purposes, we currently use "mvn versions:set ...". See dev/increment_project_versions.sh and dev/set_project_version.sh. I guess we need to adjust these scripts so that the parent POM will always get a SNAPSHOT version, right?

**Comment by dzuvic** [comment]
unfortunately i did not think about the release process itself. Question is (as always): Should the released version be visible in the VCS or not? If it the tag reflects the built source, then we have two choices:

* you have to change the version prior release, like mvn release plugin in it's prepare phase
* or the release script does  this and pushes twice...

I think, i remove the SNAPSHOT version, because both options are impractical. I suggest moving to Gradle instead of fiddling with release scripts.

**Pull request closed without merging**
